title: BSTI
baseurl: "/bsti"
permalink: pretty
markdown: kramdown
theme: just-the-docs

# Plugins
plugins:
  - jekyll-feed


just_the_docs:
  aux_links:
    "Source on GitHub": "https://github.com/fancyc-bsi/BSTI"
  search_enabled: true
  search_label: 'Search the docs...'